### PR TITLE
make webui code cleaner

### PR DESCRIPTION
**Pull request by Picus303**
This PR aims to make the code of the webui cleaner by spliting it into multiple files instead of having one giant file.

There is now a structured folder `tools/webui` that contains the same code as before but in a more readable way.

I'd like this PR to be the first of a many that'll aim to make the project easier to maintain.

### CODE REVIEW

**Comment by Picus303** [comment]
Looks like git doesn't like that I renamed `tools/webui.py` to `tools/run_webui.py`. I don't have the rights to resolve the conflict.

**Comment by AnyaCoder** [comment]
Now we updated the codebasae to ver 1.5, could you keep up with latest version ?
`https://huggingface.co/fishaudio/fish-speech-1.5`

**Comment by Picus303** [comment]
I see that there was a lot of changes. I'll wait for #698 to merge before making a new PR.

**Comment by AnyaCoder** [comment]
OK, now it's your time (

**Comment by Picus303** [comment]
I'm leaving a note here but it'll take some time. With the new structure, the API and the WebUI now share some code. Which mean that it I want to make the code clean, without global variables everywhere, I have to restructure the API as well...

**Pull request closed without merging**
