### PR TITLE
Support inference on mps device natively

### PR DESCRIPTION
**Pull request by Tps-F**
**Is this PR adding new feature or fix a BUG?**

Fix a BUG

**Is this pull request related to any issue? If yes, please link the issue.**

#187
#356

This PR enables some inference functions/feature to be handled natively on the mps rather than on the cpu.
(I'll create another PR about train.)

In previous PR(#259), It use CPUs instead of mps devices, so I use `nullcontext` to allow mps to use the context manager as well.

Also, mps don't have inductor backend, so I use `aot_eager` instead.

## Checklist

- [x] Inference
- - [x] Use mps device natively
- - [x] Use compile method

### CODE REVIEW

**Comment by AnyaCoder** [comment]
Great. How is the improvement?

**Comment by Tps-F** [comment]
Here is a result of inference using [Chinese Sentence 1 and Nahida (Genshin Impact)](https://speech.fish.audio/en/samples/)

| **Method**                    | **Time to Load Model** | **Run**  | **Token Speed** | **Bandwidth** | **Generation Time** |
|-------------------------------|------------------------|----------|-----------------|---------------|----------------------|
| **CPU**                       | 11.56 sec              | **Run 1**| 1.01 tokens/sec | 0.50 GB/s     | 278.38 sec           |
|                               |                        | **Run 2**| 1.17 tokens/sec | 0.57 GB/s     | 213.73 sec           |
|                               |                        | **Run 3**| 1.31 tokens/sec | 0.50 GB/s     | 248.36 sec           |
|                               |                        | **Average**| 1.16 tokens/sec | 0.52 GB/s     | 173.19 sec           |
| **MPS**                       | 8.42 sec               | **Run 1**| 3.25 tokens/sec | 1.59 GB/s     | 72.61 sec            |
|                               |                        | **Run 2**| 3.32 tokens/sec | 1.63 GB/s     | 67.54 sec            |
|                               |                        | **Run 3**| 3.27 tokens/sec | 1.61 GB/s     | 68.09 sec            |
|                               |                        | **Average**| 3.28 tokens/sec | 1.61 GB/s     | 69.41 sec            |
| **MPS (with compile option)** | 8.13 sec               | **Run 1**| 2.09 tokens/sec | 1.02 GB/s     | 133.20 sec           |
|                               |                        | **Run 2**| 2.22 tokens/sec | 1.09 GB/s     | 115.91 sec           |
|                               |                        | **Run 3**| 2.18 tokens/sec | 1.07 GB/s     | 119.01 sec           |
|                               |                        | **Average**| 2.16 tokens/sec | 1.06 GB/s     | 122.04 sec           |

On the same PC, using mps is **249% faster** than using cpu.

Compilation does not seem to work well, but this may be due to the GPU capacity of the M1 MacBook Air, which I believe works perfectly well in recent models.

**Comment by leng-yue** [comment]
LGTM. Can we rewrite this into a single util function (like: autocast_exclude_mps) so we can reuse it in the future?

```
    with (
        nullcontext()
        if torch.backends.mps.is_available()
        else torch.autocast(device_type="cpu", dtype=torch.bfloat16)
    ):
```

**Comment by Tps-F** [comment]
@leng-yue 
Done!
we can import it by `from fish_speech.utils import autocast_exclude_mps`
https://github.com/fishaudio/fish-speech/blob/a50ed2d3b1e7ac33877c19c05f291dde3b13fd19/fish_speech/utils/context.py#L6-L13

**Review by leng-yue — APPROVED** [review]

**Comment by leng-yue** [comment]
Cool, merged!

**Comment by amirvenus** [comment]
Could you please update the docs [here](https://github.com/fishaudio/fish-speech/blob/main/inference.ipynb) to mention how to set up on macOS Apple SoC?

Thanks!

**Comment by Gitterman69** [comment]
yes please, macos install instructions would be amazing! thanks so much

**Comment by Tps-F** [comment]
@amirvenus @Gitterman69 Sorry I'm late to reply.
I'll change the notebook and the document.

**Comment by Gitterman69** [comment]
Thanks so much! Can you ping here when its fone please! Thanks so much

**Comment by LeafYeeXYZ** [comment]
Thanks for your amazing work! But I encountered an error recently when using MPS on MacBook Air M3 in #789. Do you know what's wrong?

**Pull request merged**
