### PR TITLE
Apple's MPS backend support

### PR DESCRIPTION
**Pull request by Aintor**
**Is this PR adding new feature or fix a BUG?**

Add feature.

**Is this pull request related to any issue? If yes, please link the issue.**

#187 

Now can use `--device "mps" ` to accelerate inference speed in Mac device. 

现在可以使用`--device "mps"`来加快在Mac上的推理速度

### CODE REVIEW

**Comment by Aintor** [comment]
或者也可以在mps设备上不使用autocast，也能正常推理

**Review by leng-yue — APPROVED** [review]

**Comment by leng-yue** [comment]
Nice PR

**Comment by exceedzhang** [comment]
Yes

**Comment by cdh1991** [comment]
是这样的格式吗？ 还是会报错Torch not compiled with CUDA enabled
```
python -m tools.webui \
    --llama-checkpoint-path "checkpoints/fish-speech-1.2" \
    --decoder-checkpoint-path "checkpoints/fish-speech-1.2/firefly-gan-vq-fsq-4x1024-42hz-generator.pth" \
    --decoder-config-name firefly_gan_vq
    --compile
    --device "mps"
```

**Comment by Aintor** [comment]
> 是这样的格式吗？ 还是会报错Torch not compiled with CUDA enabled
> 
> ```
> 
> python -m tools.webui \
> 
>     --llama-checkpoint-path "checkpoints/fish-speech-1.2" \
> 
>     --decoder-checkpoint-path "checkpoints/fish-speech-1.2/firefly-gan-vq-fsq-4x1024-42hz-generator.pth" \
> 
>     --decoder-config-name firefly_gan_vq
> 
>     --compile
> 
>     --device "mps"
> 
> ```

compile一直都不支持，和我的pull没有关系，这是pytorch的问题，你可以去pytorch的repo查阅相关的issue

**Pull request merged**
