### PR TITLE
1.Supports FLAC, WAV, MP3  2.Fixed conversion path issue.

### PR DESCRIPTION
**Pull request by kenwaytis**
- 1.There were some path issues with yesterday's whisper_asr conversion script, which I have now fixed.
- 2.According to the documentation guide at https://speech.fish.audio/, the conversion script now also supports transcription of audio in all formats (FLAC, MP3, WAV).

### CODE REVIEW

**Comment by leng-yue** [comment]
Cool. We have a `list_files` util function, it supports most common audio formats.  https://github.com/fishaudio/fish-speech/blob/744622d8d0ffd1e9017ff09e7b88750e99987ee0/fish_speech/utils/file.py#L21 
Also, it will be better if you use click instead of argparse, since our other scripts are using click.

**Comment by kenwaytis** [comment]
Completed the changes as you suggested, nice code style. The sample rate change feature has also been successfully implemented.

**Comment by leng-yue** [comment]
Cool. LGTM.

**Comment by leng-yue** [comment]
Added some features in https://github.com/fishaudio/fish-speech/commit/0c56a074f73c91a56491dae340443b205d78b961

**Pull request merged**
