### PR TITLE
performance optimize

### PR DESCRIPTION
**Pull request by Stardust-minus**

### CODE REVIEW

**Comment by Qubitium** [comment]
Curious at why setting to 1 helps performance vs cores/2? Is the dataloader spawning too many threads? Not sure if 1 is the best value here.

**Comment by Stardust-minus** [comment]
> Curious at why setting to 1 helps performance vs cores/2? Is the dataloader spawning too many threads? Not sure if 1 is the best value here. 

Normally we expect every worker spawn single thread, and worker process number should equal to the cores count. In this situation the best performance will be achieved.

**Comment by Qubitium** [comment]
Curious who is spawning the threads? Unclear from simple reading of the code. Everything seems to be non-threading. 

```
    with Pool(num_workers) as p:
        for result in tqdm(p.imap_unordered(run_task, generator_fn)):
            dataset_fp.write(result)
```


Also if the worker process is the problem, maybe move the code to first line of run_task so that only the forked Process are using this env value as not to change the main process env?

**Comment by leng-yue** [comment]
Setting OMP_NUM_THREADS basically means 1 omp thread per worker. If we use N_CPU workers, there will not be racing issue. LGTM

**Pull request merged**
