### PR TITLE
Add funasr tool

### PR DESCRIPTION
**Pull request by Honst211**

### CODE REVIEW

**Comment by leng-yue** [comment]
Can we merge the whisper and funasr tool? Basically use funasr for chinese and all whisper for all other languages.

**Comment by kenwaytis** [comment]
> Can we merge the whisper and funasr tool? Basically use funasr for chinese and all whisper for all other languages.

I have implementations for funasr and whisper, but considering the addition of new dependencies and the need to change the Dockerfile, I haven't submitted them. If you think this is acceptable, I can initiate another PR later.

**Comment by leng-yue** [comment]
Added an optional deps group for asr in https://github.com/fishaudio/fish-speech/commit/675aea0519d193256af808ef63c666ac0ba08c45 . @kenwaytis We can probably merge the whisper and funasr script now.

**Comment by kenwaytis** [comment]
> Added an optional deps group for asr in [675aea0](https://github.com/fishaudio/fish-speech/commit/675aea0519d193256af808ef63c666ac0ba08c45) . @kenwaytis We can probably merge the whisper and funasr script now.

I encountered a dependency issue with Docker containers during testing: The NGC PyTorch container (nvcr.io/nvidia/pytorch:23.09-py3) does not include torchaudio, and its torch version is an unconventional 2.1.0a0+32f93b1, which prevents the installation of torchaudio.
I will attempt to resolve this.

**Comment by leng-yue** [comment]
You can add the following to the dockerfile.
```bash
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```

While this will override `nvidia/pytorch`'s default pytorch, it doesn't damage some environments required for multi node training.

**Comment by kenwaytis** [comment]
> You can add the following to the dockerfile.
> 
> ```shell
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
> ```
> 
> While this will override `nvidia/pytorch`'s default pytorch, it doesn't damage some environments required for multi node training.

Of course, we could directly add the command to install torch in the Dockerfile, but this contradicts our original purpose of using NGC's pytorch container (to avoid installing torch and Nvidia environments ourselves), doesn't it?

If you agree, we can switch to a different NGC base image (FROM xxxxx) in the Dockerfile. I am currently testing which version of the base image is suitable for our work.

(I really don't understand what Nvidia and torch are doing, releasing an official pytorch image without installing a complete environment.)

**Comment by leng-yue** [comment]
We still need the NGC base image even we reinstall pytorch. It has some libraries required for multinode training... I don't know why they don't include torchaudio too...

**Pull request closed without merging**
