### PR TITLE
[chore] add docs for macos

### PR DESCRIPTION
**Pull request by Tps-F**
**Is this PR adding new feature or fix a BUG?**

Fix BUG.

**Is this pull request related to any issue? If yes, please link the issue.**

https://discord.com/channels/1214047546020728892/1214047661758484531/1284118763767070750
https://github.com/fishaudio/fish-speech/pull/461#issuecomment-2348766593

I just added the installation instructions on macOS to the documentation.

### CODE REVIEW

**Comment by leng-yue** [comment]
Any update so we can merge this?

**Comment by Tps-F** [comment]
Sorryfor late, I have been busy studying for college exams lately and have not yet been able to look into the cause of the slowdown on the mps device.

I will add some warnings tomorrow and then I hope you will check this PR as is!

I will create another PR later on about faster inference speeds.

**Comment by Tps-F** [comment]
I'm really Sorry for the delay.
I have added about usage and current warnings.
For Chinese and Portuguese, I used a translator, so if there are any oddities, I would appreciate it if you could correct them!

**Review by leng-yue — APPROVED** [review]

**Comment by leng-yue** [comment]
LGTM, thanks for your contribution :)

**Comment by Tps-F** [comment]
Of course, thank you! 
I want to keep contributing to this project from now on as well

**Comment by brainstorm** [comment]
> If you want to perform inference on MPS, please add the `--device mps` flag.

Add the `--device mps` flag where exactly (which command)? Please provide an example.

**Pull request merged**
