### PR TITLE
Use a ratio to split train vs val set in tools/vqgan/create_train_split.py

### PR DESCRIPTION
**Pull request by TundraWork**
Currently `tools/vqgan/create_train_split.py` uses a hardcoded 100 samples of val set to split train vs val set.

This will cause an issue for dataset <= 100 samples, and perform badly for dataset <= 200 samples.

This pr changed the split to a ratio of 3:1 (3 training samples vs 1 validation sample), and will hopefully fix this problem.

### CODE REVIEW

**Comment by leng-yue** [comment]
Thanks for the PR. 3:1 is too large for larger datasets, we can add an argument to let the user select number of samples used in validation. 

- If it's a number between 0 and 1, we consider it as ratio. 
- If it's a number larger than 1, we consider it as number of samples.

Does that sounds good to you?

**Comment by TundraWork** [comment]
LGTM.

**Comment by leng-yue** [comment]
Sounds good to me. We can requires user to fill one and only one of them.

**Comment by TundraWork** [comment]
I have updated the code.

Current logic is:
- If the user specify the `--val_count` param, use the given number of validation samples
- If not, and if the user specify the `--val_ratio` param, use the given ratio to determine the number of validation samples
- If both param are not present, use a default ratio of 0.2 for validation set

**Comment by leng-yue** [comment]
Looks good to me, merged 🚀

**Pull request merged**
